---
title: "SWDchallenge 2020/04 - Small Multiples"
author: "Cedric Scherer"
date: "27th of January 2020"
output:
  html_document:
    theme: paper
    highlight: kate
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning=FALSE)
```

```{r prep}
library(tidyverse)
library(cowplot)
library(showtext)

font_add_google("Oswald", "Oswald")

## fonts
theme_set(theme_minimal(base_family = "Oswald"))

theme_update(panel.grid.major = element_blank(),
             panel.grid.minor = element_blank())
```


```{r data}
## http://football-data.co.uk/germanym.php
df_bl <- readr::read_csv(here::here("data", "D1.csv"))
```

```{r data-prep}
clubs <-
  c("RB Leipzig",
    "Borussia M'gladbach",
    "FC Bayern München",
    "Borussia Dortmund",
    "FC Schalke 04",
    "Bayer 04 Leverkusen",
    "TSG 1899 Hoffenheim",
    "SC Freiburg",
    "VfL Wolfsburg",
    "FC Augsburg",
    "1. FC Union Berlin",
    "Hertha BSC",
    "1. FSV Mainz 05",
    "Eintracht Frankfurt",
    "1. FC Köln",
    "Fortuna Düsseldorf",
    "Werder Bremen",
    "SC Paderborn 07")

df_bl_days <-
  df_bl %>%
  mutate(
    Date = lubridate::dmy(Date),
    Match = glue::glue("{HomeTeam} - {AwayTeam}"),
    Result = glue::glue("{FTHG} - {FTAG}"),
    HT = HomeTeam,
    AT = AwayTeam
  ) %>% 
  dplyr::select(Date, HomeTeam, AwayTeam, FTHG, FTAG, FTR, HS, AS, Match, Result, HT, AT) %>% 
  gather(Team, Club, -c(Date, FTHG, FTAG, FTR, HS, AS, Match, Result, HT, AT)) %>% 
  mutate(
    Goals = case_when(
      Team == "HomeTeam" ~ FTHG,
      Team == "AwayTeam" ~ FTAG
    ),
    Diff = case_when(
      Team == "HomeTeam" ~ FTHG - FTAG,
      Team == "AwayTeam" ~ FTAG - FTHG
    ),
    Score = case_when(
      FTR == "D" ~ 1,
      Team == "HomeTeam" & FTR == "H" ~ 3,
      Team == "AwayTeam" & FTR == "A" ~ 3,
      TRUE ~ 0
    ),
    Shots = case_when(
      Team == "HomeTeam" ~ HS,
      Team == "AwayTeam" ~ AS
    ),
    Opponent = case_when(
      Team == "HomeTeam" ~ AT,
      Team == "AwayTeam" ~ HT
    )
  ) %>% 
  dplyr::select(Date, Match, Result, Club, Score, Goals, Shots, Diff, Opponent) %>% 
  group_by(Club) %>% 
  arrange(Date) %>% 
  mutate(
    Day = row_number(),
    Score_sum = cumsum(Score),
    Diff_sum = cumsum(Diff),
    Goals_sum = cumsum(Goals),
  ) %>% 
  group_by(Day) %>% 
  arrange(desc(Score_sum), desc(Diff_sum), desc(Goals_sum)) %>% 
  mutate(
    Position = row_number(),
    Club = case_when(
      Club == "Augsburg" ~ "FC Augsburg",
      Club == "Bayern Munich" ~ "FC Bayern München",
      Club == "Dortmund" ~ "Borussia Dortmund", 
      Club == "Ein Frankfurt" ~ "Eintracht Frankfurt",
      Club == "FC Koln" ~ "1. FC Köln", 
      Club == "Fortuna Dusseldorf" ~ "Fortuna Düsseldorf",
      Club == "Freiburg" ~ "SC Freiburg",
      Club == "Hertha" ~ "Hertha BSC", 
      Club == "Leverkusen" ~ "Bayer 04 Leverkusen",
      Club == "M'gladbach" ~ "Borussia M'gladbach",
      Club == "Mainz" ~ "1. FSV Mainz 05",
      Club == "Paderborn" ~ "SC Paderborn 07",
      Club == "Schalke 04" ~ "FC Schalke 04",
      Club == "Union Berlin" ~ "1. FC Union Berlin",
      Club == "Wolfsburg" ~ "VfL Wolfsburg",
      Club == "Hoffenheim" ~ "TSG 1899 Hoffenheim",
      TRUE ~ Club
    ),
    Opponent = case_when(
      Opponent == "Bayern Munich" ~ "Bayern",
      Opponent == "Ein Frankfurt" ~ "Frankfurt",
      Opponent == "FC Koln" ~ "1. FC Köln", 
      Opponent == "Fortuna Dusseldorf" ~ "Fortuna",
      Opponent == "Wolfsburg" ~ "Wolfsburg",
      Opponent == "Hoffenheim" ~ "Hoffenheim",
      Opponent == "Werder Bremen" ~ "Bremen",
      TRUE ~ Opponent
    ),
    Top = if_else(!Club %in% c("RB Leipzig", "Borussia M'gladbach", "FC Bayern München", 
                               "Borussia Dortmund"), "0", "1"),
                               #"Borussia Dortmund", "FC Schalke 04", "SC Freiburg"), "0", "1"),
    Club_fct = factor(Club, levels = clubs)
  ) %>% 
  ungroup() %>% 
  arrange(Day, Position)

## Colors for all teams
cols_all <- c(
  "RB Leipzig" = "#294e88", 
  "Borussia M'gladbach" = "#0ea50e", 
  "FC Bayern München" = "#dc052d", 
  "Borussia Dortmund" = "#e4ca00", 
  "FC Schalke 04" = "#0000ca", 
  "Bayer 04 Leverkusen" = "#e32221", 
  "TSG 1899 Hoffenheim" = "#1c63b7", 
  "SC Freiburg" = "#000000", 
  "VfL Wolfsburg" = "#65b32e",
  "FC Augsburg" = "#46714d", 
  "1. FC Union Berlin" = "#d4011d",
  "Hertha BSC" = "#004d93",
  "1. FSV Mainz 05" = "#ed1c24",
  "Eintracht Frankfurt" = "#000000",
  "1. FC Köln" = "#ef343b",
  "Fortuna Düsseldorf" = "#da251d",
  "Werder Bremen" = "#008064",
  "SC Paderborn 07" = "#005ca8"
)
```

```{r efficiency, fig.width = 32, fig.height = 13.5}
vbad <- tibble(x = 0:30, ymin = x * 0, ymax = x * .1)
bad <- tibble(x = 0:30, ymin = x * .1, ymax = x * .2)
medium <- tibble(x = 0:30, ymin = x * .2, ymax = x * .3)
good <- tibble(x = 0:30, ymin = x * .3, ymax = x * .4)
vgood <- tibble(x = 0:30, ymin = x * .4, ymax = x * .5)
#### small multiples ####
annotations <- 
  tribble(
    ~Club_fct,              ~Goals, ~Shots, ~label,
    "RB Leipzig",           11,     9.5,    "Leipzig always had 10 chances\nor more and has shot the most\ngoals in a single match\n(8 vs 1. FSV Mainz 05)",
    "FC Bayern München",    13,     13,     "FCB created the most shots\nat goal in a single match\n(29 vs SV Werder Bremen)",
    "Borussia Dortmund",    8.5,    5,      "Dortmund had the least\nshots at goal of all teams\n(2 vs FC Bayern München)",
    "VfL Wolfsburg",        12.9,   10.2,   "Wolfsburg has the worst goal:shot efficiency\nof all Bundesliga clubs (8%) – they also shot\n29 times in a single match but only\nscored once (remis vs FC Schalke 04)",
    "FC Augsburg",          9.5,    6,      "Augsburg showed the highest\nefficiency in a single match\n(4 goals out of 6 shots vs\nTSG 1899 Hoffenheim)",
    "Hertha BSC",           11,     8.5,    "Hertha never shot more\nthan 16 times on\na goal in a match",
    "Fortuna Düsseldorf",   8,      5,      "Düsseldorf had the\nleast number of\nshots of all teams\n(2 vs Borussa Dortmund)"
  ) %>% 
  mutate(Club_fct = factor(Club_fct, levels = clubs))

highlight_points <-
  tribble(
    ~Club_fct,              ~Goals, ~Shots,
    "RB Leipzig",           8,      19,
    "FC Bayern München",    6,      29, 
    "Borussia Dortmund",    0,      2,  
    "VfL Wolfsburg",        1,      29, 
    "FC Augsburg",          4,      6, 
    "Fortuna Düsseldorf",   0,      2
  ) %>% 
  mutate(Club_fct = factor(Club_fct, levels = clubs))

highlight_lines <-
  tribble(
    ~Club_fct,              ~Goals, ~Shots, ~xend, ~yend,
    "RB Leipzig",           0,      10,     10,    5,
    "Hertha BSC",           0,      16,     16,    8
  ) %>% 
  mutate(Club_fct = factor(Club_fct, levels = clubs))

highlight_arrows <-
  tribble(
    ~Club_fct,              ~Goals, ~Shots, ~xend, ~yend,
    "RB Leipzig",           8,      17.9,   10.5,  9.2,
    "RB Leipzig",           4.5,    9.8,    9,     9.2,
    "FC Bayern München",    6.2,    27.9,   13,    11.5,  
    "Borussia Dortmund",    .5,     1.6,    4,     7.1,  
    "VfL Wolfsburg",        1.2,    13,     11,    11,  
    "VfL Wolfsburg",        1.1,    27.9,   12.3,  11,  
    "FC Augsburg",          4.3,    5.6,    6,     7.7,  
    "Hertha BSC",           7.2,    15.8,   8.5,   9.6,
    "Fortuna Düsseldorf",   .5,     1.6,    4.6,   6.2
  ) %>% 
  mutate(Club_fct = factor(Club_fct, levels = clubs))

facets_panel <- 
  df_bl_days %>% 
  ggplot(aes(Shots, Goals, 
             color = Club_fct,
             fill = Club_fct)) +
    ## grey-shaded areas
    geom_ribbon(data = vgood, 
                inherit.aes = F,
                aes(x = x, ymax = ymax, ymin = ymin), 
                fill = "grey70",
                alpha = .4) +
    geom_ribbon(data = good, 
                inherit.aes = F,
                aes(x = x, ymax = ymax, ymin = ymin), 
                fill = "grey70",
                alpha = .55) +
    geom_ribbon(data = medium, 
                inherit.aes = F,
                aes(x = x, ymax = ymax, ymin = ymin), 
                fill = "grey70",
                alpha = .7) +
    geom_ribbon(data = bad, 
                inherit.aes = F,
                aes(x = x, ymax = ymax, ymin = ymin), 
                fill = "grey70",
                alpha = .85) +
    geom_ribbon(data = vbad, 
                inherit.aes = F,
                aes(x = x, ymax = ymax, ymin = ymin), 
                fill = "grey70",
                alpha = 1) +
    ## annotations 1/2
    geom_segment(data = highlight_lines,
                 aes(xend = xend, 
                     yend = yend), 
                 color = "grey20",
                 size = .3,
                 linetype = "dashed") +
    geom_curve(data = highlight_arrows,
               aes(xend = xend, 
                   yend = yend), 
               curvature = -.25,
               color = "grey35", ## turn off for colored version
               size = .45,
               linetype = "dotted") +
    ## data
    geom_point(data = df_bl_days %>% 
                 group_by(Club_fct) %>% 
                 summarize(
                   avg_shots = mean(Shots), 
                   avg_goals = mean(Goals)
                  ),
               aes(avg_shots, avg_goals),
               size = 7.5, 
               shape = 23, 
               color = "grey45") +
    geom_point(color = "white",
               shape = 21, 
               alpha = .5,
               size = 3.5) +
    geom_segment(x = 30, xend = 30, 
                 y = .01, yend = 14.99, 
                 color = "grey50",
                 size = .7) +
    ## annotations 2/2
    geom_text(data = annotations,
              aes(label = label),
              family = "Oswald",
              color = "grey45", ## turn off for colored version
              size = 3.7,
              lineheight = .9) +
    geom_point(data = highlight_points,
               color = "grey20",
               fill = NA,
               shape = 21, 
               size = 4.5,
               stroke = .8) +
    facet_wrap(~ Club_fct, ncol = 6, 
               strip.position = "bottom") +
    coord_cartesian(ylim = c(0, 15), clip = "off") +
    scale_x_continuous(breaks = seq(0, 30, by = 10),
                       limits = c(0, NA), 
                       expand = c(0, 0)) +
    scale_y_continuous(breaks = seq(0, 15, by = 3),
                       labels = glue::glue("{seq(0, 50, by = 10)}%"),
                       limits = c(0, NA),
                       expand = c(.01, .01),
                       position = "right") +
    scale_color_manual(values = cols_all,
                       guide = F) +
    scale_fill_manual(values = cols_all,
                      guide = F) +
    labs(x = NULL, y = NULL) +
    theme(axis.text.x = element_blank(),
          axis.text.y = element_text(size = 12),
          axis.ticks = element_blank(),
          strip.text = element_text(color = "black", 
                                    face = "bold",
                                    size = 18),
          panel.spacing.x = unit(40, "pt"),
          panel.spacing.y = unit(25, "pt"),
          plot.margin = margin(60, 60, 60, 10))

#### legend ####
highlight <-
  tibble(
    Shots = c(14.45, 14.45, 2, 2, 9.8, 9.8, 20, 20),
    Goals = c(11.2, 10.9, 5, 4.7, 8.5, 8.2, 13.5, 13.2),
    x1 = c(NA, 14.45, NA, 2, NA, 10, NA, 20),
    x2 = c(NA, 14.45, NA, 2, NA, 10, NA, 20),
    y1 = c(NA, 9.8, NA, 4.2, NA, 7.7, NA, 12.7),
    y2 = c(NA, 2.41, NA, 0, NA, 5, NA, 1),
    face = rep(c("bold", "plain"), 4),
    label = c("Average Goal Efficiency",
              "Ratio of goals to shots based\non the mean of all 17 matches",
              "Low Efficiency Match",
              "few shots and no goals",
              "High Efficiency Match",
              "5 out of 10 shots were goals",
              "Low Efficiency Match",
              "many shots and few goals")
  )

legend <-
  df_bl_days %>% 
  filter(Club == "Borussia Dortmund") %>% 
  mutate(
    Goals = if_else(Opponent == "Leverkusen", 5, Goals),
    Shots = if_else(Opponent == "Leverkusen", 10, Shots),
    Shots = if_else(Opponent %in% c("1. FC Köln", "RB Leipzig"), 13, Shots)
  ) %>% 
  ggplot(aes(Shots, Goals)) +
    geom_ribbon(data = vgood, 
                inherit.aes = F,
                aes(x = x, ymax = ymax, ymin = ymin), 
                fill = "grey70",
                alpha = .4) +
    geom_ribbon(data = good, 
                inherit.aes = F,
                aes(x = x, ymax = ymax, ymin = ymin), 
                fill = "grey70",
                alpha = .55) +
    geom_ribbon(data = medium, 
                inherit.aes = F,
                aes(x = x, ymax = ymax, ymin = ymin), 
                fill = "grey70",
                alpha = .7) +
    geom_ribbon(data = bad, 
                inherit.aes = F,
                aes(x = x, ymax = ymax, ymin = ymin), 
                fill = "grey70",
                alpha = .85) +
    geom_ribbon(data = vbad, 
                inherit.aes = F,
                aes(x = x, ymax = ymax, ymin = ymin), 
                fill = "grey70",
                alpha = 1) +
    geom_segment(data = highlight,
                 aes(x = x1, xend = x2, 
                     y = y1, yend = y2)) +
    geom_text(data = highlight %>% filter(face == "bold"),
               aes(label = label), 
               size = 5.3,
               family = "Oswald",
               fontface = "bold") +
    geom_text(data = highlight %>% filter(face == "plain"),
              aes(label = label), 
              size = 5.3,
              family = "Oswald",
              vjust = 1,
              lineheight = .95) +
    geom_point(data = tibble(Shots = 14.45, Goals = 2.41),
               shape = 23, 
               color = "grey40", 
               fill = "grey20", 
               size = 9) +
    geom_point(shape = 21, 
               color = "white",
               fill =  "grey40",
               size = 6) +
    geom_segment(x = 30, xend = 30, 
                 y = .01, yend = 14.99, 
                 color = "grey50",
                 size = 1) +
    geom_text(data = tibble(
                       Shots = rep(27.2, 6),
                       Goals = c(seq(1.7, 12, length.out = 5), .7),
                       label = c(as.character(glue::glue("{seq(0, 40, by = 10)}–{seq(10, 50, by = 10)}%")), 
                                 "Goal\nEfficiency")
                     ),
              aes(label = label),
              family = "Oswald",
              fontface = "bold",
              lineheight = .8,
              size = 5) + 
    annotate("text", x = 3, y = 13.5, 
             label = "How to Read:", 
             family = "Oswald", 
             size = 10, 
             fontface = "bold") +
    coord_cartesian(ylim = c(0, 15), clip = "off") +
    scale_x_continuous(breaks = seq(0, 30, by = 5),
                       limits = c(-1.5, 30.1), 
                       expand = c(0, 0)) +
    scale_y_continuous(breaks = seq(0, 15, by = 3),
                       limits = c(-.05, NA),
                       expand = c(.01, .01),
                       position = "right") +
    scale_color_manual(values = cols_all,
                       guide = F) +
    scale_fill_manual(values = cols_all,
                      guide = F) +
    labs(x = "Shots", y = "Goals",
         caption = "Visualization by Cédric Scherer") +
    theme(axis.text = element_text(size = 16),
          axis.title = element_text(size = 20,
                                    face = "bold"),
          axis.ticks = element_blank(),
          plot.caption = element_text(size = 18,
                                      face = "bold",
                                      hjust = 0,
                                      margin = margin(120, 0, 0, 0)),
          plot.margin = margin(150, 80, 30, 120))


title <- ggplot(data.frame(x = 1:2, y = 1:10)) +
  labs(x = NULL, y = NULL,
       title = "RB Leipzig and Borussia Dortmund Make the Most of Their Opportunities",
       subtitle = "The small multiples show each club's goal:shot efficiency in the first season 2019/2020 of the 1. Bundesliga. However, while Borussia Dortmund also had very bad matches with only 2 chances,\nthe Autumn champion RB Leipzig always scored minimum one goal and shot at least ten times on the opponent's goal in all 17 matches! Of all Bundesliga clubs, RB Leipzig also shot the most goals – 8 against Mainz.") +
  theme(line = element_blank(),
        axis.text = element_blank(),
        axis.line.x = element_blank(),
        plot.title = element_text(size = 40, 
                                  face = "bold",
                                  hjust = .5, 
                                  margin = margin(t = 60, b = 15)),
        plot.subtitle = element_text(family = "Oswald", 
                                     size = 22,
                                     color = "grey45", 
                                     hjust = .5, 
                                     lineheight = .95),
        plot.margin = margin(20, 100, 20, 100))

#### full panel ####
bottom_row <- plot_grid(legend, facets_panel, ncol = 2, rel_widths = c(.35, .65))
plot_grid(title, bottom_row, nrow = 2, rel_heights = c(.1, .9))

ggsave(here::here("plots", "2020_01", "SWD_2020_01_SmallMultiples.pdf"), 
       width = 32, height = 13.5, device = cairo_pdf)
```

***

```{r session-info}
sessionInfo()
```

